### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Headscracher** [Headscracher/HumbleBundleBot#1]
- [ ] Steam-Store Integration ( Games in Discord Post verlinken )
- [ ] Anpassbare Gruppen Berechtigungen
- [ ] Asynchroner Versand der Discord Nachrichten
- [ ] Andere Bundle-Typen abfragen/abfangen
- [x] Add Steam review to footer
- [ ] Get further review data from Steam directly
- [ ] Bundle requests
- [ ] Age restrictions

**Comment by Headscracher** [comment]
Closing project
